class Commands:
    LEECH = "leech@LeechV3_bot"
    PURGE = "purge@LeechV3_bot"
    PAUSEALL = "pauseall@LeechV3_bot"
    RESUMEALL = "resumeall@LeechV3_bot"
    STATUS = "status@LeechV3_bot"
    SETTINGS = "settings@LeechV3_bot"
    EXEC = "exec@LeechV3_bot"
    UPLOAD = "upload@LeechV3_bot"
    YTDL = "ytdl@LeechV3_bot"
    PYTDL = "pytdl@LeechV3_bot"
    ABOUT = "about@LeechV3_bot"
    GETLOGS = "getlogs@LeechV3_bot"
    SERVER = "server@LeechV3_bot"
    USERSETTINGS = "usetting@LeechV3_bot"
    INSTADL = "instadl@LeechV3_bot"
